package fr.kristenjestin.mue.data.local.database

import android.content.res.AssetManager
import fr.kristenjestin.mue.domain.model.CiqualCatalogue
import fr.kristenjestin.mue.domain.model.Food
import fr.kristenjestin.mue.domain.model.FoodId
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import java.io.IOException

/**
 * Reads the embedded Ciqual subset out of `assets/ciqual/catalogue-<version>.json` (PRD_FOOD
 * 9.1, 20.2).
 *
 * **The version is discovered from the file name, never from the file.** That is what lets the
 * seeding guard run on every cold start for the price of a directory listing: knowing whether
 * there is work to do must not mean parsing two hundred kilobytes of JSON, any more than it must
 * mean opening Room. It is also what lets the real asset — generated by `packages/ciqual`, which
 * names it after `ciqual.source.json`'s own `version` — replace the committed fixture with no
 * code change at all: no constant here names a version.
 *
 * If more than one catalogue is present, the greatest name wins, so a newly dropped
 * `catalogue-ciqual-2025.1.json` supersedes the placeholder without anyone having to remember to
 * delete it first.
 *
 * Everything the frozen [CiqualCatalogue] can validate is validated by it, and by nothing here:
 * `fromJsonOrNull` is the one parser, and `CiqualEntry.toFoodOrNull` is the one place a range is
 * checked. [idsByCode] reads exactly one field the frozen type cannot carry — see its comment.
 */
internal object CiqualCatalogueAsset {

    const val DIRECTORY = "ciqual"
    private const val PREFIX = "catalogue-"
    private const val SUFFIX = ".json"

    private val lenient = Json { ignoreUnknownKeys = true }

    /**
     * The version of the catalogue shipped in this APK, or null if none is. A directory listing:
     * no file is opened and no JSON is parsed.
     */
    fun availableVersion(assets: AssetManager): String? = try {
        assets.list(DIRECTORY)
            .orEmpty()
            .filter { it.startsWith(PREFIX) && it.endsWith(SUFFIX) }
            .maxOrNull()
            ?.removePrefix(PREFIX)
            ?.removeSuffix(SUFFIX)
            ?.takeIf { it.isNotEmpty() }
    } catch (_: IOException) {
        null
    }

    fun pathOf(version: String): String = "$DIRECTORY/$PREFIX$version$SUFFIX"

    fun readOrNull(assets: AssetManager, version: String): String? = try {
        assets.open(pathOf(version)).use { it.readBytes().decodeToString() }
    } catch (_: IOException) {
        null
    }

    /**
     * The identifier of each entry, keyed by its Ciqual code.
     *
     * **The ids come from the asset; none is derived here.** `packages/ciqual` computes a
     * name-based UUID per `alim_code` once, at build time, precisely so that the same food has
     * the same primary key on every install — a journal line's `sourceRef` and a recipe
     * ingredient's `food_id` are synchronised, so an id minted on the device would make the same
     * apple a different food on every phone. `FoodId.random()` is therefore never called on this
     * path, and an entry the asset gives no id for is skipped rather than given one.
     *
     * It is read straight from the JSON because the frozen `CiqualEntry` has no `id` field and
     * its parser ignores unknown keys, so the value would be silently dropped by the very call
     * that validates everything else. This is the one field read outside
     * [CiqualCatalogue.fromJsonOrNull], and it is read without interpreting it: a string is
     * taken as it stands or not at all.
     */
    fun idsByCode(raw: String): Map<String, String> = try {
        val entries = (lenient.parseToJsonElement(raw) as? JsonObject)
            ?.get("entries") as? JsonArray
        entries.orEmpty()
            .mapNotNull { element ->
                val entry = element as? JsonObject ?: return@mapNotNull null
                val code = (entry["code"] as? JsonPrimitive)?.takeIf { it.isString }?.content
                val id = (entry["id"] as? JsonPrimitive)?.takeIf { it.isString }?.content
                if (code.isNullOrBlank() || id.isNullOrBlank()) null else code to id
            }
            .toMap()
    } catch (_: IllegalArgumentException) {
        emptyMap()
    }

    /**
     * The foods of one catalogue, in asset order, minus every entry the frozen validator or the
     * id rule rejects. A malformed row is dropped and the rest of the subset still installs:
     * losing one food out of five hundred must not leave a phone with no catalogue at all.
     */
    fun foodsOf(raw: String): List<Food> {
        val catalogue = CiqualCatalogue.fromJsonOrNull(raw) ?: return emptyList()
        val ids = idsByCode(raw)
        return catalogue.entries.mapNotNull { entry ->
            val id = ids[entry.code] ?: return@mapNotNull null
            entry.toFoodOrNull(sourceVersion = catalogue.version, id = FoodId(id))
        }
    }

    /** The version the asset declares inside itself, which is what gets recorded as installed. */
    fun versionOf(raw: String): String? = CiqualCatalogue.fromJsonOrNull(raw)?.version
}
