// What the build prints.
//
// The report is not logging. A catalogue is 1 000 rows nobody reads, generated by rules
// nobody re-derives, and the only way a change to those rules is reviewable is if the
// build states its consequences in numbers a reviewer can diff: how many rows per group,
// how many ratios were derived and from which pairs, how many trace values were dropped
// rather than turned into zeros, how many portions attached. A subset that silently
// doubled, or a Ciqual release that stopped determining fibre, both show up here as a
// number that moved.

import type { BuildResult } from "./catalogue";
import type { Pair } from "./pairing";
import type { CiqualTable } from "./table";
import type { SubsetResult, SubsetRules } from "./subset";

export interface ReportInput {
  readonly version: string;
  readonly table: CiqualTable;
  readonly pairs: readonly Pair[];
  readonly subset: SubsetResult;
  readonly build: BuildResult;
  readonly rules: SubsetRules;
  readonly archiveSha256: string;
  readonly catalogueSha256: string;
  readonly bytes: number;
}

function pad(value: string | number, width: number): string {
  return String(value).padStart(width);
}

export function formatReport(input: ReportInput): string {
  const { table, pairs, subset, build, rules } = input;
  const lines: string[] = [];
  const say = (text = "") => lines.push(text);

  say(`Ciqual catalogue ${input.version}`);
  say(`  source archive sha256  ${input.archiveSha256}`);
  say(`  catalogue    sha256    ${input.catalogueSha256}`);
  say(`  catalogue    bytes     ${input.bytes.toLocaleString("en-GB")}`);
  say();

  // --- what the source said -------------------------------------------------------
  const counts = table.counts;
  const total = counts.value + counts.notDetermined + counts.traces + counts.lessThan;
  say(`Source: ${table.foods.size} foods, ${total} cells across the six constituents read`);
  say(`  ${pad(counts.value, 7)}  measured values (an explicit 0 among them is a known zero)`);
  say(`  ${pad(counts.notDetermined, 7)}  "-"       not determined -> null, never 0`);
  say(`  ${pad(counts.traces, 7)}  "traces"  present below quantification -> null`);
  say(`  ${pad(counts.lessThan, 7)}  "< x"     present below a stated limit -> null`);
  say(
    `           ${counts.traces + counts.lessThan} trace-class cells dropped to null; mapping them to 0 would claim` +
      ` knowledge PRD_FOOD 13.1 forbids`,
  );
  say();

  // --- cooked ratios --------------------------------------------------------------
  const byVerdict = (verdict: string) => pairs.filter((pair) => pair.verdict === verdict);
  const oneEntry = byVerdict("oneEntry");
  say(`Cooked ratios (PRD_FOOD 8.6): ${pairs.length} raw/cooked pairs found`);
  say(
    `  ${pad(oneEntry.length, 5)}  one entry  - only water moved, reference row carries the ratio`,
  );
  say(`  ${pad(byVerdict("twoEntries").length, 5)}  two entries - composition changed, no ratio`);
  say(`  ${pad(byVerdict("noWater").length, 5)}  no ratio    - water not determined on one side`);
  say(
    `  ${pad(byVerdict("ratioOutOfBounds").length, 5)}  no ratio    - outside PRD_FOOD 15's 0.3..5`,
  );
  say(
    `  ${pad(byVerdict("ratioNegligible").length, 5)}  no ratio    - within 15 % of 1, so the two states weigh the same` +
      " as far as this module is concerned",
  );
  const ungated = oneEntry.filter((pair) => pair.disagreeingUngated.length > 0);
  if (ungated.length > 0) {
    say();
    say(
      `  ${pad(ungated.length, 5)}  of those were accepted over a non-gating disagreement.` +
        " Ciqual's own two rows",
    );
    say("         disagree about these constituents by more than a boil can explain, so the");
    say("         disagreement is between two measurements and not between two foods:");
    for (const pair of ungated) {
      const detail = pair.comparisons
        .filter((entry) => pair.disagreeingUngated.includes(entry.constituent))
        .map(
          (entry) =>
            `${entry.constituent} ${entry.reference} vs ${entry.rescaled?.toFixed(2)} rescaled` +
            ` (${((entry.deltaRatio ?? 0) * 100).toFixed(0)} %)`,
        )
        .join(", ");
      say(`         ${pair.reference.nameEng} -> ${detail}`);
    }
  }
  say();
  say(
    `  ratios attached to shipped rows: ${build.catalogue.entries.filter((e) => e.cookedRatioThousandths !== undefined).length}`,
  );
  for (const pair of oneEntry.slice(0, 200)) {
    if (!build.catalogue.entries.some((entry) => entry.code === pair.reference.code)) continue;
    say(
      `    ${pad(pair.reference.code, 6)}  ${((pair.ratioThousandths ?? 0) / 1000).toFixed(3)}  ` +
        `${pair.reference.nameEng}  <-  ${pair.cooked.nameEng}`,
    );
  }
  say();

  // --- subset ---------------------------------------------------------------------
  say("Subset (PRD_FOOD 9.5), rows removed by pass:");
  const reasons = [
    ["subGroupNotAllowed", "sub-group not in the allowlist"],
    ["subSubGroupDenied", "sub-sub-group denied"],
    ["excludedPattern", "brand / variety / label / provenance / packaged"],
    ["noEnergy", "no energy value, so it can never contribute to a total"],
    ["mergedIntoReference", "cooked half of a pair, folded into its reference"],
    ["clustered", "within 15 % of a row already kept"],
    ["clusterFull", "one food already has its maximum number of rows"],
    ["override", "subset.overrides.json"],
  ] as const;
  for (const [key, label] of reasons) {
    say(`  ${pad(subset.droppedByReason[key], 6)}  ${label}`);
  }
  say(`  ${pad(subset.selected.length, 6)}  kept`);
  if (build.shortened.length > 0) {
    say(
      `  ${pad(build.shortened.length, 6)}  names shortened to PRD_FOOD 15's 80 characters, food-first so the` +
        " row still names the same thing:",
    );
    for (const row of build.shortened)
      say(`          ${row.code} "${row.from}"
            -> "${row.to}"`);
  }
  if (build.rejected.length > 0) {
    say(`  ${pad(build.rejected.length, 6)}  rejected by PRD_FOOD 15's bounds at emit time:`);
    for (const row of build.rejected) say(`          ${row.code} ${row.name}: ${row.reason}`);
  }
  say();

  const perGroup = new Map<string, number>();
  for (const { food } of subset.selected) {
    perGroup.set(food.groupCode, (perGroup.get(food.groupCode) ?? 0) + 1);
  }
  say("Rows per Ciqual group:");
  for (const code of [...perGroup.keys()].sort()) {
    say(`  ${code}  ${pad(perGroup.get(code) ?? 0, 5)}  ${table.groupNames.get(code) ?? "?"}`);
  }
  say(`      ${pad(build.catalogue.entries.length, 5)}  total`);

  const { min, max } = rules.targetSize;
  if (build.catalogue.entries.length < min || build.catalogue.entries.length > max) {
    say();
    say(
      `  NOTE: ${build.catalogue.entries.length} rows is outside the reviewed target of ${min}..${max}.`,
    );
    say("        The rules in subset.rules.json are what produced it; widen or tighten");
    say("        them there rather than trimming the output.");
  }
  say();

  // --- portions -------------------------------------------------------------------
  say(`Usual portions (PRD_FOOD 8.2), hand-maintained in portions.json:`);
  say(`  ${pad(build.portionsAttached, 6)}  attached to a shipped row`);
  if (build.portionsUnmatched.length > 0) {
    say(
      `  ${pad(build.portionsUnmatched.length, 6)}  written for a food the subset does not ship: ` +
        build.portionsUnmatched.join(", "),
    );
  }
  say();
  say(
    `  overrides in use: ${subset.droppedByReason.override} drop, ` +
      `see subset.overrides.json for keeps`,
  );

  return lines.join("\n");
}
