package fr.kristenjestin.mue.data.remote.sync

import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

/**
 * The wire, hand written, mirroring `packages/contracts/src` field for field.
 *
 * These types are generated by nothing. `packages/contracts` is the source of truth and Zod is
 * where it is stated; what keeps this file honest is [ContractFixtures] — the sixteen instances
 * the contracts package emits into `src/test/resources/contract`, parsed and re-serialised by a
 * JVM test that needs no server, no network and no emulator. A field the server adds and this
 * file ignores shows up as a diff; a field this file requires and the server drops fails to
 * parse. That test is the entire reason these DTOs may be written by hand at all.
 *
 * Three rules run through every declaration here, and each one is a decision the contracts
 * package already argued for:
 *
 * 1. **A counter is a string.** `revision` and `sequence` cross the wire as canonical decimal
 *    text, never as a JSON number: past 2^53 a JSON number gives Kotlin no precision guarantee,
 *    and a number invites arithmetic on a value the protocol treats as opaque. They are `String`
 *    here for exactly that reason, and [SyncNumbers] is the one place that converts.
 * 2. **A cursor is opaque.** [PullPageDto.nextCursor] is stored and returned verbatim. Nothing
 *    in this package parses it, orders by it, compares it or reconstructs one.
 * 3. **A union is sealed.** `op` and `status` discriminate real Kotlin hierarchies, so a branch
 *    that carries no `nextCursor` genuinely has no `nextCursor` to read.
 */

/** The aggregate types V1 can express on the wire. `AGGREGATE_TYPES` in `primitives.ts`. */
const val WIRE_AGGREGATE_MEASUREMENT: String = "measurement"

/** `MEASUREMENT_PAYLOAD_VERSION_1` in `measurement.ts`. */
const val WIRE_MEASUREMENT_PAYLOAD_VERSION: Int = 1

/** `PUSH_MAX_MUTATIONS` in `sync.ts`: one request carries at most this many mutations. */
const val WIRE_PUSH_MAX_MUTATIONS: Int = 200

/** `PULL_DEFAULT_LIMIT` and `PULL_MAX_LIMIT` in `sync.ts`. */
const val WIRE_PULL_DEFAULT_LIMIT: Int = 100
const val WIRE_PULL_MAX_LIMIT: Int = 500

/**
 * `MueError` — FR-SYNC-007's structured, actionable business error.
 *
 * [code] is a `String` and not an `enum class`, and that is deliberate rather than lazy: the Zod
 * schema types it as a dotted-lowercase *pattern* precisely so a server that adds a code does
 * not break a client whose parser is strict. An enum here would turn a new server error into a
 * parse failure that hides the real error. [SyncErrorCodes] names the ones V1 defines, and an
 * unrecognised code degrades to a generic non-retryable failure.
 *
 * The four optional fields are absent rather than null when they do not apply — `.optional()`
 * in Zod, not `.nullable()` — which is why they carry defaults and [SyncJson] never encodes
 * defaults.
 */
@Serializable
data class MueErrorDto(
    val code: String,
    val message: String,
    val retryable: Boolean,
    val aggregateType: String? = null,
    val aggregateId: String? = null,
    /** Dotted path of the offending field, for `sync.missing_required_field`. */
    val field: String? = null,
    /** The revision the server actually holds, so a client can rebase instead of guessing. */
    val currentRevision: String? = null,
)

/** `Origin` — who authored a mutation (PRD 12.1), nested here because the envelope nests it. */
@Serializable
data class OriginDto(
    val type: String,
    /** Device, agent or process identifier. Opaque, and never a display name. */
    val id: String,
) {
    companion object {
        const val TYPE_ANDROID = "android"
        const val TYPE_AGENT = "agent"
        const val TYPE_SERVER = "server"
    }
}

/**
 * `AggregateMeta` — PRD 12.1's eight fields, kept flat because that is the shape the stores
 * hold: `sync_aggregate_state` has `origin_type` and `origin_id` as two columns, and a mapper
 * that unpacks an object into two columns on one side and packs it back on the other is a
 * mapper that will one day forget one of them.
 *
 * [deletedAt] is required-and-nullable, not optional: it is set exactly when the aggregate is a
 * tombstone (FR-SYNC-005), and "the key is absent" would be a third state the protocol does not
 * have. It therefore carries no default, so [SyncJson] always writes it.
 */
@Serializable
data class AggregateMetaDto(
    val id: String,
    val revision: String,
    val createdAt: String,
    val updatedAt: String,
    val deletedAt: String?,
    val originType: String,
    val originId: String,
    val lastMutationId: String,
)

/**
 * `MeasurementPayloadV1` — one weight for one calendar day.
 *
 * [weightCg] is a whole count of hundredths of a kilogram, exactly as Room stores it, so the
 * mapper on both ends is an identity and no float ever reintroduces the drift Mue's integer
 * unit exists to avoid. [date] repeats the aggregate identifier because PRD 12.2 requires an
 * upsert to carry the complete aggregate: a payload that only made sense next to its envelope
 * could not be replayed from the journal on its own.
 */
@Serializable
data class MeasurementPayloadV1Dto(
    val date: String,
    val weightCg: Int,
)

/**
 * `MutationEnvelope` — one unit of work in the outbox (PRD 12.2).
 *
 * Sealed on `op`, mirroring Zod's `discriminatedUnion("op", …)`: "an upsert has a payload and a
 * delete has none" is then a shape the Kotlin type system enforces rather than a comment. The
 * upsert branch is a single member today; a second aggregate type nests a union on
 * `aggregateType` inside it and changes nothing else here.
 *
 * [mutationId] is FR-SYNC-006's idempotency key and the whole of the client's no-duplicate
 * guarantee. It is *never* minted in this package: it is read from `sync_mutations.mutation_id`,
 * where the transaction that wrote the business row put it, so a retry of a lost response sends
 * the identifier the server already has and gets its stored result back.
 */
@OptIn(ExperimentalSerializationApi::class)
@Serializable
@JsonClassDiscriminator("op")
sealed interface MutationEnvelopeDto {
    val mutationId: String
    val aggregateType: String
    val aggregateId: String

    /**
     * The revision the author believed it was editing, or null when it believed the aggregate
     * did not exist yet — PRD 12.2's "si elle existe". Null is not zero: zero would claim a
     * revision the server issued.
     */
    val baseRevision: String?
    val payloadSchemaVersion: Int
    val origin: OriginDto

    /** The author's own clock. For display and audit; never for ordering (PRD 12.3). */
    val clientOccurredAt: String
}

/**
 * No property here carries a default, and that is a round-trip requirement rather than a style.
 * [SyncJson] does not encode defaults — it cannot, or [PullRequestDto.limit] would be written as
 * a null the server refuses — so a defaulted `aggregateType` would simply vanish from the body
 * whenever it held its usual value, and the contract test would report it as a missing field.
 * The expected values are named as constants at the top of this file instead.
 */
@Serializable
@SerialName("upsert")
data class MeasurementUpsertMutationDto(
    override val mutationId: String,
    override val aggregateType: String,
    override val aggregateId: String,
    override val baseRevision: String?,
    override val payloadSchemaVersion: Int,
    val payload: MeasurementPayloadV1Dto,
    override val origin: OriginDto,
    override val clientOccurredAt: String,
) : MutationEnvelopeDto

/**
 * A delete carries `"payload": null` — the key present, the value null.
 *
 * Zod says `z.null()`, not `.optional()`, so omitting the key is a validation failure on the
 * server. [EncodeDefault] is what makes the default value be written anyway: [SyncJson] does not
 * encode defaults, because `PullRequestDto.limit` is genuinely optional and a `"limit": null`
 * would be refused by an `.optional()` that does not accept null. One rule cannot serve both,
 * so the exception is annotated where it applies rather than loosened globally.
 */
@OptIn(ExperimentalSerializationApi::class)
@Serializable
@SerialName("delete")
data class DeleteMutationDto(
    override val mutationId: String,
    override val aggregateType: String,
    override val aggregateId: String,
    override val baseRevision: String?,
    override val payloadSchemaVersion: Int,
    override val origin: OriginDto,
    override val clientOccurredAt: String,
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    val payload: String? = null,
) : MutationEnvelopeDto

/**
 * `SyncChange` — one accepted entry of the server journal (PRD 12.3), as the client receives it.
 *
 * [sequence] is the journal position. It is carried, stored nowhere, and used for nothing: the
 * client's only pagination state is the opaque cursor. Reading it would be the first step
 * towards reconstructing one.
 */
@OptIn(ExperimentalSerializationApi::class)
@Serializable
@JsonClassDiscriminator("op")
sealed interface SyncChangeDto {
    val sequence: String
    val aggregateType: String
    val aggregateId: String
    val payloadSchemaVersion: Int
    val meta: AggregateMetaDto
}

@Serializable
@SerialName("upsert")
data class MeasurementUpsertChangeDto(
    override val sequence: String,
    override val aggregateType: String,
    override val aggregateId: String,
    override val payloadSchemaVersion: Int,
    val payload: MeasurementPayloadV1Dto,
    override val meta: AggregateMetaDto,
) : SyncChangeDto

@OptIn(ExperimentalSerializationApi::class)
@Serializable
@SerialName("delete")
data class DeleteChangeDto(
    override val sequence: String,
    override val aggregateType: String,
    override val aggregateId: String,
    override val payloadSchemaVersion: Int,
    override val meta: AggregateMetaDto,
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    val payload: String? = null,
) : SyncChangeDto

/** `PushRequest` — a batch of local mutations, in outbox order. */
@Serializable
data class PushRequestDto(
    val mutations: List<MutationEnvelopeDto>,
)

/**
 * `MutationResult` — one result per submitted mutation, so a single invalid mutation cannot
 * block the batch behind it (FR-SYNC-007).
 *
 * `duplicate` is not an error and is treated exactly like `applied`: it is the server replaying
 * a stored result for a mutation id it has already seen, which is FR-SYNC-006's guarantee that
 * a lost response costs a round trip and never a duplicate.
 */
@OptIn(ExperimentalSerializationApi::class)
@Serializable
@JsonClassDiscriminator("status")
sealed interface MutationResultDto {
    val mutationId: String
}

@Serializable
@SerialName("applied")
data class MutationAppliedDto(
    override val mutationId: String,
    val revision: String,
    val sequence: String,
) : MutationResultDto

@Serializable
@SerialName("duplicate")
data class MutationDuplicateDto(
    override val mutationId: String,
    val revision: String,
    val sequence: String,
) : MutationResultDto

@Serializable
@SerialName("rejected")
data class MutationRejectedDto(
    override val mutationId: String,
    val error: MueErrorDto,
) : MutationResultDto

@Serializable
data class PushResponseDto(
    val results: List<MutationResultDto>,
    val serverTime: String,
)

/**
 * `PullRequest` — reads the journal after [cursor].
 *
 * [cursor] is required-and-nullable and therefore has no default: null on an initial sync means
 * "from the beginning", and an absent key would be a third state. [limit] is `.optional()` in
 * Zod and not `.nullable()`, so it must be *omitted* when unset — which is what a default plus
 * [SyncJson]'s `encodeDefaults = false` produces.
 *
 * [supportedSchemaVersions] is required, and it is what turns PRD 12.4 into a server-enforced
 * invariant rather than a client-side hope: the client states what it can apply, and a server
 * holding anything newer answers [PullUpgradeRequiredDto] instead of a page the client would
 * half-apply.
 */
@Serializable
data class PullRequestDto(
    val cursor: String?,
    val limit: Int? = null,
    val supportedSchemaVersions: Map<String, List<Int>>,
)

/**
 * `PullResponse` — a sealed hierarchy, and the single most load-bearing shape in this file.
 *
 * A flat class with a nullable `nextCursor` would compile, parse both branches and be wrong:
 * the engine could read a cursor on a response that protocol-wise has none, and advance past
 * data it cannot apply. [PullUpgradeRequiredDto] genuinely has no `nextCursor` property, so
 * that mistake is not a bug to be caught in review — it does not typecheck.
 *
 * Both outcomes are HTTP 200 with a discriminated body, matching push: a rejected mutation and
 * an unapplicable payload are business results, not transport failures, and a non-2xx would
 * make a client throw before the body, and its actionable [MueErrorDto], were ever parsed.
 */
@OptIn(ExperimentalSerializationApi::class)
@Serializable
@JsonClassDiscriminator("status")
sealed interface PullResponseDto {
    val serverTime: String

    /**
     * FR-SYNC-008: the age of the last Android sync the server knows about, so no reader infers
     * a freshness guarantee the server cannot give. Null when no device has ever synchronised.
     */
    val lastAndroidSyncAt: String?
}

@Serializable
@SerialName("ok")
data class PullPageDto(
    val changes: List<SyncChangeDto>,
    /** Advance to this, verbatim, and only after every change above is applied locally. */
    val nextCursor: String,
    val hasMore: Boolean,
    override val serverTime: String,
    override val lastAndroidSyncAt: String?,
) : PullResponseDto

@Serializable
@SerialName("upgrade_required")
data class PullUpgradeRequiredDto(
    val error: MueErrorDto,
    override val serverTime: String,
    override val lastAndroidSyncAt: String?,
) : PullResponseDto

/** `ErrorResponse` — the single envelope every non-2xx body on `/api/v1` uses. */
@Serializable
data class ErrorResponseDto(
    val error: MueErrorDto,
)

/**
 * The codes `errors.ts` defines. Named constants rather than an enum, for the reason
 * [MueErrorDto.code] gives: the wire type is a pattern, and an unknown code must degrade
 * instead of failing to parse.
 */
object SyncErrorCodes {
    const val AUTH_FORBIDDEN = "auth.forbidden"
    const val AUTH_UNAUTHENTICATED = "auth.unauthenticated"
    const val HTTP_NOT_FOUND = "http.not_found"
    const val SERVER_INTERNAL = "server.internal"
    const val SERVER_UNAVAILABLE = "server.unavailable"
    const val SYNC_AGGREGATE_DELETED = "sync.aggregate_deleted"
    const val SYNC_INVALID_CURSOR = "sync.invalid_cursor"
    const val SYNC_INVALID_PAYLOAD = "sync.invalid_payload"
    const val SYNC_MISSING_REQUIRED_FIELD = "sync.missing_required_field"
    const val SYNC_REVISION_CONFLICT = "sync.revision_conflict"
    const val SYNC_UNKNOWN_AGGREGATE_TYPE = "sync.unknown_aggregate_type"
    const val SYNC_UPGRADE_REQUIRED = "sync.upgrade_required"

    /**
     * Not a wire code: what the client records when it could not reach the server at all.
     * FR-SYNC-008 makes that a normal state away from home, so it is stored and never alarms.
     */
    const val CLIENT_UNREACHABLE = "client.unreachable"

    /** Not a wire code: the body did not match the contract. Retrying an identical request
     *  would produce an identical failure, so this is not retryable. */
    const val CLIENT_MALFORMED_RESPONSE = "client.malformed_response"

    /** Not a wire code: no server is paired, so there is nothing to synchronise with. */
    const val CLIENT_NOT_PAIRED = "client.not_paired"
}
