package fr.kristenjestin.mue.data.remote.sync

import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonEncoder
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * The wire, hand written, mirroring `packages/contracts/src` field for field.
 *
 * These types are generated by nothing. `packages/contracts` is the source of truth and Zod is
 * where it is stated; what keeps this file honest is [ContractFixtures] — the sixteen instances
 * the contracts package emits into `src/test/resources/contract`, parsed and re-serialised by a
 * JVM test that needs no server, no network and no emulator. A field the server adds and this
 * file ignores shows up as a diff; a field this file requires and the server drops fails to
 * parse. That test is the entire reason these DTOs may be written by hand at all.
 *
 * Three rules run through every declaration here, and each one is a decision the contracts
 * package already argued for:
 *
 * 1. **A counter is a string.** `revision` and `sequence` cross the wire as canonical decimal
 *    text, never as a JSON number: past 2^53 a JSON number gives Kotlin no precision guarantee,
 *    and a number invites arithmetic on a value the protocol treats as opaque. They are `String`
 *    here for exactly that reason, and [SyncNumbers] is the one place that converts.
 * 2. **A cursor is opaque.** [PullPageDto.nextCursor] is stored and returned verbatim. Nothing
 *    in this package parses it, orders by it, compares it or reconstructs one.
 * 3. **A union is sealed.** `op` and `status` discriminate real Kotlin hierarchies, so a branch
 *    that carries no `nextCursor` genuinely has no `nextCursor` to read.
 *
 * ## Two discriminators, and what that costs Kotlin
 *
 * The mutation and change unions are discriminated **twice**: `op` says whether a payload is
 * present, and on an upsert `aggregateType` says which schema that payload follows. Zod nests
 * two `discriminatedUnion`s and is done. kotlinx.serialization cannot: a sealed hierarchy has
 * exactly one `@JsonClassDiscriminator`, and two subclasses both named `@SerialName("upsert")`
 * are refused outright — the measurement and the health profile would collide on the only key
 * the framework has.
 *
 * So [MutationEnvelopeSerializer] and [SyncChangeSerializer] read the two keys by hand. The
 * hierarchies stay sealed, which is what rule 3 is actually about, and the `when` inside each
 * serializer is exhaustive over the sealed interface — so a branch added to the contract and
 * forgotten here fails to compile, where a missing annotation would simply have been absent.
 * `op` is therefore a **declared property** on every member rather than a key the framework
 * injects, and it carries [EncodeDefault] because [SyncJson] does not encode defaults.
 */

/** The aggregate types the wire can express. `AGGREGATE_TYPES` in `primitives.ts`. */
const val WIRE_AGGREGATE_MEASUREMENT: String = "measurement"
const val WIRE_AGGREGATE_HEALTH_PROFILE: String = "healthProfile"

/**
 * `HEALTH_PROFILE_AGGREGATE_ID` in `health-profile.ts`, where the Zod envelope pins it as a
 * literal rather than an opaque identifier.
 *
 * PRD 13.4 gives an account exactly one profile, so its identity is a constant and not
 * something a device mints. Two phones that each invented a UUID for "their" profile would
 * create two aggregates, both valid and both synchronised, and no merge rule could say which
 * one *is* the profile. A constant makes the rival unrepresentable instead of unlikely — and it
 * is the same `'me'` `HealthProfileEntity.ROW_ID` already keys the local table by.
 */
const val WIRE_HEALTH_PROFILE_AGGREGATE_ID: String = "me"

/** The two values of `op`. Declared properties here, for the reason [MutationEnvelopeDto] gives. */
const val WIRE_OP_UPSERT: String = "upsert"
const val WIRE_OP_DELETE: String = "delete"

/** `MEASUREMENT_PAYLOAD_VERSION_1` in `measurement.ts`. */
const val WIRE_MEASUREMENT_PAYLOAD_VERSION: Int = 1

/** `HEALTH_PROFILE_PAYLOAD_VERSION_1` in `health-profile.ts`. */
const val WIRE_HEALTH_PROFILE_PAYLOAD_VERSION: Int = 1

/** `PUSH_MAX_MUTATIONS` in `sync.ts`: one request carries at most this many mutations. */
const val WIRE_PUSH_MAX_MUTATIONS: Int = 200

/** `PULL_DEFAULT_LIMIT` and `PULL_MAX_LIMIT` in `sync.ts`. */
const val WIRE_PULL_DEFAULT_LIMIT: Int = 100
const val WIRE_PULL_MAX_LIMIT: Int = 500

/**
 * `MueError` — FR-SYNC-007's structured, actionable business error.
 *
 * [code] is a `String` and not an `enum class`, and that is deliberate rather than lazy: the Zod
 * schema types it as a dotted-lowercase *pattern* precisely so a server that adds a code does
 * not break a client whose parser is strict. An enum here would turn a new server error into a
 * parse failure that hides the real error. [SyncErrorCodes] names the ones V1 defines, and an
 * unrecognised code degrades to a generic non-retryable failure.
 *
 * The four optional fields are absent rather than null when they do not apply — `.optional()`
 * in Zod, not `.nullable()` — which is why they carry defaults and [SyncJson] never encodes
 * defaults.
 */
@Serializable
data class MueErrorDto(
    val code: String,
    val message: String,
    val retryable: Boolean,
    val aggregateType: String? = null,
    val aggregateId: String? = null,
    /** Dotted path of the offending field, for `sync.missing_required_field`. */
    val field: String? = null,
    /** The revision the server actually holds, so a client can rebase instead of guessing. */
    val currentRevision: String? = null,
)

/** `Origin` — who authored a mutation (PRD 12.1), nested here because the envelope nests it. */
@Serializable
data class OriginDto(
    val type: String,
    /** Device, agent or process identifier. Opaque, and never a display name. */
    val id: String,
) {
    companion object {
        const val TYPE_ANDROID = "android"
        const val TYPE_AGENT = "agent"
        const val TYPE_SERVER = "server"
    }
}

/**
 * `AggregateMeta` — PRD 12.1's eight fields, kept flat because that is the shape the stores
 * hold: `sync_aggregate_state` has `origin_type` and `origin_id` as two columns, and a mapper
 * that unpacks an object into two columns on one side and packs it back on the other is a
 * mapper that will one day forget one of them.
 *
 * [deletedAt] is required-and-nullable, not optional: it is set exactly when the aggregate is a
 * tombstone (FR-SYNC-005), and "the key is absent" would be a third state the protocol does not
 * have. It therefore carries no default, so [SyncJson] always writes it.
 */
@Serializable
data class AggregateMetaDto(
    val id: String,
    val revision: String,
    val createdAt: String,
    val updatedAt: String,
    val deletedAt: String?,
    val originType: String,
    val originId: String,
    val lastMutationId: String,
)

/**
 * `MeasurementPayloadV1` — one weight for one calendar day.
 *
 * [weightCg] is a whole count of hundredths of a kilogram, exactly as Room stores it, so the
 * mapper on both ends is an identity and no float ever reintroduces the drift Mue's integer
 * unit exists to avoid. [date] repeats the aggregate identifier because PRD 12.2 requires an
 * upsert to carry the complete aggregate: a payload that only made sense next to its envelope
 * could not be replayed from the journal on its own.
 */
@Serializable
data class MeasurementPayloadV1Dto(
    val date: String,
    val weightCg: Int,
)

/**
 * `HealthProfilePayloadV1` — the height and birth date of PRD 13.4, the account's one profile.
 *
 * Both properties are **nullable and carry no default**, which is not a detail. Zod says
 * `.nullable()` and not `.optional()`, so `null` is a stated empty value and an absent key is
 * not a value at all. That distinction is what PRD 13.4's field-by-field merge runs on: the
 * server compares each field against the version its author was editing, so "the user cleared
 * their height" has to be expressible and has to be distinguishable from "this client said
 * nothing about heights". No default here means [SyncJson] always writes both keys, and it
 * means a body that dropped one fails to parse rather than quietly reading as null.
 *
 * [heightCm] is a whole count of centimetres, the unit `UserProfile.heightCm` already holds and
 * `UserProfile.HEIGHT_RANGE_CM` already bounds. [birthDate] is an ISO-8601 calendar date, as
 * every date in Mue is, so lexicographic order is chronological order.
 */
@Serializable
data class HealthProfilePayloadV1Dto(
    val heightCm: Int?,
    val birthDate: String?,
)

/**
 * `MutationEnvelope` — one unit of work in the outbox (PRD 12.2).
 *
 * Sealed on `op`, mirroring Zod's `discriminatedUnion("op", …)`: "an upsert has a payload and a
 * delete has none" is then a shape the Kotlin type system enforces rather than a comment. The
 * upsert branch is a single member today; a second aggregate type nests a union on
 * `aggregateType` inside it and changes nothing else here.
 *
 * [mutationId] is FR-SYNC-006's idempotency key and the whole of the client's no-duplicate
 * guarantee. It is *never* minted in this package: it is read from `sync_mutations.mutation_id`,
 * where the transaction that wrote the business row put it, so a retry of a lost response sends
 * the identifier the server already has and gets its stored result back.
 */
@Serializable(with = MutationEnvelopeSerializer::class)
sealed interface MutationEnvelopeDto {
    val mutationId: String
    val aggregateType: String
    val aggregateId: String

    /**
     * `"upsert"` or `"delete"`, declared rather than injected.
     *
     * It was the class discriminator until the contract grew a second upsert branch. Two
     * subclasses cannot share one `@SerialName`, so the discrimination moved into
     * [MutationEnvelopeSerializer] and this became an ordinary property the concrete
     * serializers write themselves.
     */
    val op: String

    /**
     * The revision the author believed it was editing, or null when it believed the aggregate
     * did not exist yet — PRD 12.2's "si elle existe". Null is not zero: zero would claim a
     * revision the server issued.
     */
    val baseRevision: String?
    val payloadSchemaVersion: Int
    val origin: OriginDto

    /** The author's own clock. For display and audit; never for ordering (PRD 12.3). */
    val clientOccurredAt: String
}

/**
 * No property here carries a default, and that is a round-trip requirement rather than a style.
 * [SyncJson] does not encode defaults — it cannot, or [PullRequestDto.limit] would be written as
 * a null the server refuses — so a defaulted `aggregateType` would simply vanish from the body
 * whenever it held its usual value, and the contract test would report it as a missing field.
 * The expected values are named as constants at the top of this file instead.
 */
@OptIn(ExperimentalSerializationApi::class)
@Serializable
data class MeasurementUpsertMutationDto(
    override val mutationId: String,
    override val aggregateType: String,
    override val aggregateId: String,
    override val baseRevision: String?,
    override val payloadSchemaVersion: Int,
    val payload: MeasurementPayloadV1Dto,
    override val origin: OriginDto,
    override val clientOccurredAt: String,
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    override val op: String = WIRE_OP_UPSERT,
) : MutationEnvelopeDto

/**
 * The upsert of the single health profile (PRD 13.4).
 *
 * [aggregateId] defaults to [WIRE_HEALTH_PROFILE_AGGREGATE_ID] and is written always, because
 * the Zod envelope pins it as a literal: a mutation naming anything else does not parse on the
 * server, so a second device cannot open a rival profile even by accident. The default lives
 * here rather than at the call site so there is one place the constant is spelled.
 *
 * There is **no delete counterpart**, and the server refuses one. PRD 13.4 describes fields
 * that become empty, never a profile that ceases to exist; a tombstone would claim the latter,
 * and FR-SYNC-005 would then use it to refuse the user's own next edit as a resurrection.
 * Clearing a height is this branch with `heightCm = null`.
 */
@OptIn(ExperimentalSerializationApi::class)
@Serializable
data class HealthProfileUpsertMutationDto(
    override val mutationId: String,
    override val baseRevision: String?,
    override val payloadSchemaVersion: Int,
    val payload: HealthProfilePayloadV1Dto,
    override val origin: OriginDto,
    override val clientOccurredAt: String,
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    override val aggregateType: String = WIRE_AGGREGATE_HEALTH_PROFILE,
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    override val aggregateId: String = WIRE_HEALTH_PROFILE_AGGREGATE_ID,
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    override val op: String = WIRE_OP_UPSERT,
) : MutationEnvelopeDto

/**
 * A delete carries `"payload": null` — the key present, the value null.
 *
 * Zod says `z.null()`, not `.optional()`, so omitting the key is a validation failure on the
 * server. [EncodeDefault] is what makes the default value be written anyway: [SyncJson] does not
 * encode defaults, because `PullRequestDto.limit` is genuinely optional and a `"limit": null`
 * would be refused by an `.optional()` that does not accept null. One rule cannot serve both,
 * so the exception is annotated where it applies rather than loosened globally.
 */
@OptIn(ExperimentalSerializationApi::class)
@Serializable
data class DeleteMutationDto(
    override val mutationId: String,
    override val aggregateType: String,
    override val aggregateId: String,
    override val baseRevision: String?,
    override val payloadSchemaVersion: Int,
    override val origin: OriginDto,
    override val clientOccurredAt: String,
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    val payload: String? = null,
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    override val op: String = WIRE_OP_DELETE,
) : MutationEnvelopeDto

/**
 * `SyncChange` — one accepted entry of the server journal (PRD 12.3), as the client receives it.
 *
 * [sequence] is the journal position. It is carried, stored nowhere, and used for nothing: the
 * client's only pagination state is the opaque cursor. Reading it would be the first step
 * towards reconstructing one.
 */
@Serializable(with = SyncChangeSerializer::class)
sealed interface SyncChangeDto {
    val sequence: String
    val aggregateType: String
    val aggregateId: String
    val payloadSchemaVersion: Int
    val meta: AggregateMetaDto

    /** Declared rather than injected, for the reason [MutationEnvelopeDto.op] gives. */
    val op: String
}

@OptIn(ExperimentalSerializationApi::class)
@Serializable
data class MeasurementUpsertChangeDto(
    override val sequence: String,
    override val aggregateType: String,
    override val aggregateId: String,
    override val payloadSchemaVersion: Int,
    val payload: MeasurementPayloadV1Dto,
    override val meta: AggregateMetaDto,
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    override val op: String = WIRE_OP_UPSERT,
) : SyncChangeDto

/**
 * The health profile as the server hands it back: **merged**, not echoed.
 *
 * PRD 13.4 lets the server keep a field this device never touched, so the payload here can
 * differ from the one the device pushed a moment earlier — and applying it is how a phone whose
 * stale birth date was merged away converges instead of believing its own version stood.
 */
@OptIn(ExperimentalSerializationApi::class)
@Serializable
data class HealthProfileUpsertChangeDto(
    override val sequence: String,
    override val payloadSchemaVersion: Int,
    val payload: HealthProfilePayloadV1Dto,
    override val meta: AggregateMetaDto,
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    override val aggregateType: String = WIRE_AGGREGATE_HEALTH_PROFILE,
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    override val aggregateId: String = WIRE_HEALTH_PROFILE_AGGREGATE_ID,
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    override val op: String = WIRE_OP_UPSERT,
) : SyncChangeDto

@OptIn(ExperimentalSerializationApi::class)
@Serializable
data class DeleteChangeDto(
    override val sequence: String,
    override val aggregateType: String,
    override val aggregateId: String,
    override val payloadSchemaVersion: Int,
    override val meta: AggregateMetaDto,
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    val payload: String? = null,
    @EncodeDefault(EncodeDefault.Mode.ALWAYS)
    override val op: String = WIRE_OP_DELETE,
) : SyncChangeDto

/**
 * The two-level discrimination `packages/contracts` states and kotlinx.serialization has no
 * annotation for.
 *
 * Zod writes `discriminatedUnion("op", [discriminatedUnion("aggregateType", […]), delete])`.
 * The framework equivalent would need two `@JsonClassDiscriminator`s on one hierarchy, and it
 * would need two subclasses to answer to `@SerialName("upsert")` — which it refuses. So the
 * dispatch is written out, once per hierarchy, and it is written *exhaustively*: the `when` in
 * [serialize] covers a sealed interface, so a branch added to [MutationEnvelopeDto] and
 * forgotten here does not compile.
 *
 * Nothing here is reflective. `JsonContentPolymorphicSerializer` would have done the reading
 * half in three lines and left the writing half to `value::class.serializerOrNull()`, a
 * reflective lookup that R8 has to be told to keep; an explicit branch has no such dependency
 * and names the concrete serializer where a reader can see it.
 *
 * A body that is not a JSON object, or that carries an `op` or an `aggregateType` this build
 * does not know, raises [SerializationException] — which is what [ContractDrift] turns into a
 * sentence naming the fixture and the discriminator, and what `SyncEngine` treats as one
 * unreadable row rather than a failed synchronisation.
 */
@OptIn(ExperimentalSerializationApi::class)
object MutationEnvelopeSerializer : KSerializer<MutationEnvelopeDto> {

    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("MutationEnvelope")

    override fun serialize(encoder: Encoder, value: MutationEnvelopeDto) {
        val output = encoder.asJsonEncoder("a mutation")
        output.encodeJsonElement(
            when (value) {
                is MeasurementUpsertMutationDto ->
                    output.json.encodeToJsonElement(MeasurementUpsertMutationDto.serializer(), value)

                is HealthProfileUpsertMutationDto ->
                    output.json.encodeToJsonElement(
                        HealthProfileUpsertMutationDto.serializer(),
                        value,
                    )

                is DeleteMutationDto ->
                    output.json.encodeToJsonElement(DeleteMutationDto.serializer(), value)
            },
        )
    }

    override fun deserialize(decoder: Decoder): MutationEnvelopeDto {
        val input = decoder.asJsonDecoder("a mutation")
        val element = input.decodeJsonElement().asJsonObject("a mutation")
        return when (val op = element.discriminator("op", "a mutation")) {
            WIRE_OP_UPSERT -> when (
                val type = element.discriminator("aggregateType", "an upsert")
            ) {
                WIRE_AGGREGATE_MEASUREMENT ->
                    input.json.decodeFromJsonElement(
                        MeasurementUpsertMutationDto.serializer(),
                        element,
                    )

                WIRE_AGGREGATE_HEALTH_PROFILE ->
                    input.json.decodeFromJsonElement(
                        HealthProfileUpsertMutationDto.serializer(),
                        element,
                    )

                else -> throw SerializationException(
                    "this build has no upsert branch for aggregateType \"$type\"",
                )
            }

            WIRE_OP_DELETE ->
                input.json.decodeFromJsonElement(DeleteMutationDto.serializer(), element)

            else -> throw SerializationException("a mutation is an upsert or a delete, not \"$op\"")
        }
    }
}

/** The read side of the same two-level union, and the same argument. */
@OptIn(ExperimentalSerializationApi::class)
object SyncChangeSerializer : KSerializer<SyncChangeDto> {

    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("SyncChange")

    override fun serialize(encoder: Encoder, value: SyncChangeDto) {
        val output = encoder.asJsonEncoder("a change")
        output.encodeJsonElement(
            when (value) {
                is MeasurementUpsertChangeDto ->
                    output.json.encodeToJsonElement(MeasurementUpsertChangeDto.serializer(), value)

                is HealthProfileUpsertChangeDto ->
                    output.json.encodeToJsonElement(
                        HealthProfileUpsertChangeDto.serializer(),
                        value,
                    )

                is DeleteChangeDto ->
                    output.json.encodeToJsonElement(DeleteChangeDto.serializer(), value)
            },
        )
    }

    override fun deserialize(decoder: Decoder): SyncChangeDto {
        val input = decoder.asJsonDecoder("a change")
        val element = input.decodeJsonElement().asJsonObject("a change")
        return when (val op = element.discriminator("op", "a change")) {
            WIRE_OP_UPSERT -> when (
                val type = element.discriminator("aggregateType", "an upsert change")
            ) {
                WIRE_AGGREGATE_MEASUREMENT ->
                    input.json.decodeFromJsonElement(
                        MeasurementUpsertChangeDto.serializer(),
                        element,
                    )

                WIRE_AGGREGATE_HEALTH_PROFILE ->
                    input.json.decodeFromJsonElement(
                        HealthProfileUpsertChangeDto.serializer(),
                        element,
                    )

                else -> throw SerializationException(
                    "this build has no upsert branch for aggregateType \"$type\"",
                )
            }

            WIRE_OP_DELETE ->
                input.json.decodeFromJsonElement(DeleteChangeDto.serializer(), element)

            else -> throw SerializationException("a change is an upsert or a delete, not \"$op\"")
        }
    }
}

private fun Encoder.asJsonEncoder(what: String): JsonEncoder =
    this as? JsonEncoder
        ?: throw SerializationException("$what can only be written as JSON")

private fun Decoder.asJsonDecoder(what: String): JsonDecoder =
    this as? JsonDecoder
        ?: throw SerializationException("$what can only be read as JSON")

private fun JsonElement.asJsonObject(what: String): JsonObject =
    this as? JsonObject ?: throw SerializationException("$what is a JSON object")

/**
 * One discriminator value, or a failure naming the key that was missing.
 *
 * `jsonPrimitive` alone would throw `IllegalArgumentException`, which is not a
 * [SerializationException] and would therefore escape every `catch` in this package — a body
 * with `"op": 3` in it would crash a synchronisation instead of marking one row unreadable.
 */
private fun JsonObject.discriminator(key: String, what: String): String {
    val value = this[key] ?: throw SerializationException("$what carries no \"$key\"")
    val primitive = runCatching { value.jsonPrimitive }.getOrNull()
    if (primitive == null || !primitive.isString) {
        throw SerializationException("$what has a \"$key\" that is not a string")
    }
    return primitive.content
}

/** `PushRequest` — a batch of local mutations, in outbox order. */
@Serializable
data class PushRequestDto(
    val mutations: List<MutationEnvelopeDto>,
)

/**
 * `MutationResult` — one result per submitted mutation, so a single invalid mutation cannot
 * block the batch behind it (FR-SYNC-007).
 *
 * `duplicate` is not an error and is treated exactly like `applied`: it is the server replaying
 * a stored result for a mutation id it has already seen, which is FR-SYNC-006's guarantee that
 * a lost response costs a round trip and never a duplicate.
 */
@OptIn(ExperimentalSerializationApi::class)
@Serializable
@JsonClassDiscriminator("status")
sealed interface MutationResultDto {
    val mutationId: String
}

@Serializable
@SerialName("applied")
data class MutationAppliedDto(
    override val mutationId: String,
    val revision: String,
    val sequence: String,
) : MutationResultDto

@Serializable
@SerialName("duplicate")
data class MutationDuplicateDto(
    override val mutationId: String,
    val revision: String,
    val sequence: String,
) : MutationResultDto

@Serializable
@SerialName("rejected")
data class MutationRejectedDto(
    override val mutationId: String,
    val error: MueErrorDto,
) : MutationResultDto

@Serializable
data class PushResponseDto(
    val results: List<MutationResultDto>,
    val serverTime: String,
)

/**
 * `PullRequest` — reads the journal after [cursor].
 *
 * [cursor] is required-and-nullable and therefore has no default: null on an initial sync means
 * "from the beginning", and an absent key would be a third state. [limit] is `.optional()` in
 * Zod and not `.nullable()`, so it must be *omitted* when unset — which is what a default plus
 * [SyncJson]'s `encodeDefaults = false` produces.
 *
 * [supportedSchemaVersions] is required, and it is what turns PRD 12.4 into a server-enforced
 * invariant rather than a client-side hope: the client states what it can apply, and a server
 * holding anything newer answers [PullUpgradeRequiredDto] instead of a page the client would
 * half-apply.
 */
@Serializable
data class PullRequestDto(
    val cursor: String?,
    val limit: Int? = null,
    val supportedSchemaVersions: Map<String, List<Int>>,
)

/**
 * `PullResponse` — a sealed hierarchy, and the single most load-bearing shape in this file.
 *
 * A flat class with a nullable `nextCursor` would compile, parse both branches and be wrong:
 * the engine could read a cursor on a response that protocol-wise has none, and advance past
 * data it cannot apply. [PullUpgradeRequiredDto] genuinely has no `nextCursor` property, so
 * that mistake is not a bug to be caught in review — it does not typecheck.
 *
 * Both outcomes are HTTP 200 with a discriminated body, matching push: a rejected mutation and
 * an unapplicable payload are business results, not transport failures, and a non-2xx would
 * make a client throw before the body, and its actionable [MueErrorDto], were ever parsed.
 */
@OptIn(ExperimentalSerializationApi::class)
@Serializable
@JsonClassDiscriminator("status")
sealed interface PullResponseDto {
    val serverTime: String

    /**
     * FR-SYNC-008: the age of the last Android sync the server knows about, so no reader infers
     * a freshness guarantee the server cannot give. Null when no device has ever synchronised.
     */
    val lastAndroidSyncAt: String?
}

@Serializable
@SerialName("ok")
data class PullPageDto(
    val changes: List<SyncChangeDto>,
    /** Advance to this, verbatim, and only after every change above is applied locally. */
    val nextCursor: String,
    val hasMore: Boolean,
    override val serverTime: String,
    override val lastAndroidSyncAt: String?,
) : PullResponseDto

@Serializable
@SerialName("upgrade_required")
data class PullUpgradeRequiredDto(
    val error: MueErrorDto,
    override val serverTime: String,
    override val lastAndroidSyncAt: String?,
) : PullResponseDto

/** `ErrorResponse` — the single envelope every non-2xx body on `/api/v1` uses. */
@Serializable
data class ErrorResponseDto(
    val error: MueErrorDto,
)

/**
 * The codes `errors.ts` defines. Named constants rather than an enum, for the reason
 * [MueErrorDto.code] gives: the wire type is a pattern, and an unknown code must degrade
 * instead of failing to parse.
 */
object SyncErrorCodes {
    const val AUTH_FORBIDDEN = "auth.forbidden"
    const val AUTH_UNAUTHENTICATED = "auth.unauthenticated"
    const val HTTP_NOT_FOUND = "http.not_found"
    const val SERVER_INTERNAL = "server.internal"
    const val SERVER_UNAVAILABLE = "server.unavailable"
    const val SYNC_AGGREGATE_DELETED = "sync.aggregate_deleted"
    const val SYNC_INVALID_CURSOR = "sync.invalid_cursor"
    const val SYNC_INVALID_PAYLOAD = "sync.invalid_payload"
    const val SYNC_MISSING_REQUIRED_FIELD = "sync.missing_required_field"
    const val SYNC_REVISION_CONFLICT = "sync.revision_conflict"
    const val SYNC_UNKNOWN_AGGREGATE_TYPE = "sync.unknown_aggregate_type"
    const val SYNC_UPGRADE_REQUIRED = "sync.upgrade_required"

    /**
     * Not a wire code: what the client records when it could not reach the server at all.
     * FR-SYNC-008 makes that a normal state away from home, so it is stored and never alarms.
     */
    const val CLIENT_UNREACHABLE = "client.unreachable"

    /** Not a wire code: the body did not match the contract. Retrying an identical request
     *  would produce an identical failure, so this is not retryable. */
    const val CLIENT_MALFORMED_RESPONSE = "client.malformed_response"

    /** Not a wire code: no server is paired, so there is nothing to synchronise with. */
    const val CLIENT_NOT_PAIRED = "client.not_paired"
}
